[22:42:15] INFO     Starting a new run of the 'Classic' flow with the tag 'RUN_2025-10-27_22-42-15'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         flow.py:655
[22:42:15] INFO     Starting…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sequential.py:294
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Verilator Lint ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[22:42:15] VERBOSE  Running 'Verilator.Lint' at 'openlane/user_project_wrapper/runs/RUN_2025-10-27_22-42-15/01-verilator-lint'…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             step.py:1146
[22:42:19] VERBOSE  Logging subprocess to 'openlane/user_project_wrapper/runs/RUN_2025-10-27_22-42-15/01-verilator-lint/verilator-lint.log'…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                step.py:1342
%Warning-PINMISSING: /workspace/peripheral-example/verilog/rtl/user_project_wrapper.v:85:16: Cell has missing pin: 'VPWR'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
... For warning description see https://verilator.org/warn/PINMISSING?v=5.018                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
... Use "/* verilator lint_off PINMISSING */" and lint_on around source to disable this message.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
%Warning-PINMISSING: /workspace/peripheral-example/verilog/rtl/user_project_wrapper.v:85:16: Cell has missing pin: 'VGND'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
%Error-PINNOTFOUND: /workspace/peripheral-example/verilog/rtl/user_project_wrapper.v:87:6: Pin not found: 'vccd1'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
%Error-PINNOTFOUND: /workspace/peripheral-example/verilog/rtl/user_project_wrapper.v:88:6: Pin not found: 'vssd1'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
%Error: Exiting due to 2 error(s)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Lint Timing Errors Checker ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[22:42:19] VERBOSE  Running 'Checker.LintTimingConstructs' at 'openlane/user_project_wrapper/runs/RUN_2025-10-27_22-42-15/02-checker-linttimingconstructs'…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 step.py:1146
[22:42:19] INFO     Check for Lint Timing Errors clear.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   checker.py:404
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Lint Errors Checker ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[22:42:19] VERBOSE  Running 'Checker.LintErrors' at 'openlane/user_project_wrapper/runs/RUN_2025-10-27_22-42-15/03-checker-linterrors'…                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     step.py:1146
[22:42:19] ERROR    2 Lint errors found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  checker.py:128
Classic - Stage 3 - Lint Errors Checker ━                                         2/78 0:00:03
[22:42:19] ERROR    The following error was encountered while running the flow:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          __main__.py:190
                    2 Lint errors found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
[22:42:19] ERROR    LibreLane will now quit.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             __main__.py:191
